### ISSUE TITLE
Edit Project Post

### ISSUE THREAD

**Issue by houndhunger** [houndhunger/project-path#6]
**User story:**
As the owner of a post, I can edit its details so that I can make updates or corrections.

**Acceptance Criteria:**
- [x] Users can update the title, description, and image of the post.
- [x] Edited posts display the changes instantly on the page.
- [ ] #27

**Tasks:**
- [x] Create an edit post form with fields for title, description, image galley and title image.
- [x] Connect the form to the API endpoint for updating posts.
- [ ] #24
- [ ] #25
- [x] Ensure instant rendering of the changes on the page.
- [ ] #26
