### ISSUE TITLE
Delete Project Post

### ISSUE THREAD

**Issue by houndhunger** [houndhunger/project-path#7]
**User story:**
As the owner of a post, I can delete it so that I can control my content visibility.

**Acceptance Criteria:**
- [x] A delete option is available on each of my posts.
- [ ] #28
- [x] Deleted posts are removed immediately from the portfolio page.

**Tasks:**
- [x] Add a delete button to each post owned by the user.
- [ ] #29
- [x] Connect the delete functionality to the API endpoint for post removal.
- [x] Remove the deleted post from the frontend view instantly.
- [ ] #30
